# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
use_modular_headers!

  # Pods for Example
  pod 'DogFetcher'
  pod 'Kingfisher'

  target 'ExampleTests' do
      inherit! :complete
  end

end
